name: Main Pipeline

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Pull the latest image
    - name: Pull Docker Image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest

    # Run container
    - name: Run Docker Container
      run: |
        docker run -d --name test-container -p 8082:80 ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest

    # Test website accessibility
    - name: Test Container
      run: curl -I localhost:8082

    # Cleanup
    - name: Cleanup
      run: docker rm -f test-container
